package org.adligo.tests4j_4gwt.client.model.example;

import java.util.ArrayList;
import java.util.List;

import org.adligo.tests4j.models.shared.common.TrialType;
import org.adligo.tests4j.models.shared.trials.I_Trial;
import org.adligo.tests4j_4gwt.client.model.run.GwtTrialDescription;
import org.adligo.tests4j_4gwt.client.model.run.I_GwtMethodWrapper;
import org.adligo.tests4j_4gwt.client.model.run.I_GwtTrialDescription;
import org.adligo.tests4j_4gwt.client.model.run.I_GwtTrialWrapper;

/**
 * this binding would be autogenerated
 * @author scott
 *
 */
public class ExampleGwtTrialWrapper implements I_GwtTrialWrapper {
	private ExampleGwtTrial trial = new ExampleGwtTrial();

	@Override
	public String getName() {
		return trial.getClass().getName();
	}

	@Override
	public I_GwtMethodWrapper getBeforeTrial() {
		return null;
	}

	@Override
	public I_GwtMethodWrapper getBeforeTests() {
		return new I_GwtMethodWrapper() {
			
			@Override
			public void run() {
				trial.beforeTests();
			}
			
			@Override
			public String getName() {
				return "beforeTests";
			}
		};
	}

	@Override
	public List<I_GwtMethodWrapper> getTests() {
		List<I_GwtMethodWrapper> tests = new ArrayList<I_GwtMethodWrapper>();
		tests.add(get_testJavaAnnotation());
		tests.add(get_testJavaIo());
		tests.add(get_testJavaLang());
		tests.add(get_testJavaLogging());
		tests.add(get_testJavaMath());
		tests.add(get_testJavaSql());
		tests.add(get_testJavaUtil());
		return tests;
	}

	private I_GwtMethodWrapper get_testJavaLang() {
		return new I_GwtMethodWrapper() {

			@Override
			public String getName() {
				return "testJavaLang";
			}

			@Override
			public void run() {
				trial.testJavaLang();
			}
			
		};
	}
	
	private I_GwtMethodWrapper get_testJavaAnnotation() {
		return new I_GwtMethodWrapper() {

			@Override
			public String getName() {
				return "testJavaAnnotation";
			}

			@Override
			public void run() {
				trial.testJavaAnnotation();
			}
			
		};
	}
	
	private I_GwtMethodWrapper get_testJavaMath() {
		return new I_GwtMethodWrapper() {

			@Override
			public String getName() {
				return "testJavaMath";
			}

			@Override
			public void run() {
				trial.testJavaMath();
			}
			
		};
	}
	
	private I_GwtMethodWrapper get_testJavaIo() {
		return new I_GwtMethodWrapper() {

			@Override
			public String getName() {
				return "testJavaIo";
			}

			@Override
			public void run() {
				trial.testJavaIo();
			}
			
		};
	}
	
	private I_GwtMethodWrapper get_testJavaSql() {
		return new I_GwtMethodWrapper() {

			@Override
			public String getName() {
				return "testJavaSql";
			}

			@Override
			public void run() {
				trial.testJavaSql();
			}
			
		};
	}
	
	private I_GwtMethodWrapper get_testJavaLogging() {
		return new I_GwtMethodWrapper() {

			@Override
			public String getName() {
				return "testJavaLogging";
			}

			@Override
			public void run() {
				trial.testJavaLogging();
			}
			
		};
	}
	
	private I_GwtMethodWrapper get_testJavaUtil() {
		return new I_GwtMethodWrapper() {

			@Override
			public String getName() {
				return "testJavaUtil";
			}

			@Override
			public void run() {
				trial.testJavaUtil();
			}
			
		};
	}
	@Override
	public I_GwtMethodWrapper getAfterTests() {
		return new I_GwtMethodWrapper() {
			
			@Override
			public void run() {
				trial.afterTests();
			}
			
			@Override
			public String getName() {
				return "afterTests";
			}
		};
	}

	@Override
	public I_GwtMethodWrapper getAfterTrial() {
		return null;
	}

	@Override
	public I_Trial getTrial() {
		return trial;
	}

	@Override
	public I_GwtTrialDescription getDescription() {
		GwtTrialDescription desc = new GwtTrialDescription();
		desc.setTrialName(trial.getClass().getName());
		desc.setType(TrialType.SourceFileTrial);
		return desc;
	}
	

}
